# Generated by Django 4.1.7 on 2023-02-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_team_delete_teams"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="twiter_link",
            new_name="twitter_link",
        ),
    ]
