# Generated by Django 4.1.7 on 2023-03-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_rename_twiter_link_team_twitter_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="desgination",
            new_name="designation",
        ),
    ]
