# Generated by Django 4.1.5 on 2023-01-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0002_my_books_author_my_books_is_bestselling_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_books",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
