# Generated by Django 4.1.5 on 2023-01-25 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0004_author_alter_my_books_slug_alter_my_books_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="my_books",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="book_outlet.author",
            ),
        ),
    ]
