# Generated by Django 4.1.5 on 2023-01-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0007_country_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=3),
        ),
    ]
