# Generated by Django 4.1.7 on 2023-03-21 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=80)),
                ("phone", models.CharField(max_length=80)),
                ("car_id", models.IntegerField()),
                ("customer_need", models.CharField(max_length=80)),
                ("car_title", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=80)),
                ("state", models.CharField(max_length=80)),
                ("message", models.TextField(blank=True)),
                ("user_id", models.IntegerField(blank=True)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
