# Generated by Django 4.1.7 on 2023-03-05 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_alter_car_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_featured",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2000, 2000),
                    (2001, 2001),
                    (2002, 2002),
                    (2003, 2003),
                    (2004, 2004),
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                ]
            ),
        ),
    ]
