# Generated by Django 4.1.7 on 2023-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_alter_car_created_date_alter_car_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="doors",
            field=models.CharField(
                choices=[("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(max_length=30),
        ),
    ]
