# Generated by Django 4.1.7 on 2023-03-14 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0011_alter_car_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
